"""
Sentinel Agent - Core threat hunting logic with CockroachDB vector memory
"""

import json
import logging
import os
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass
import asyncio

import boto3
import psycopg2
import numpy as np
from psycopg2.extras import RealDictCursor

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@dataclass
class SecurityEvent:
    """Security event structure"""
    event_id: Optional[str]
    user_id: Optional[str]
    event_type: str
    source_ip: str
    action: str
    timestamp: datetime
    raw_log: Dict
    embedding: Optional[List[float]] = None

@dataclass
class ThreatDecision:
    """Agent decision structure"""
    event_id: str
    threat_score: float
    reasoning: str
    action_taken: str
    similar_events: List[Dict]

class SentinelAgent:
    """
    Core Sentinel agent that implements the observe-embed-retrieve-reason-act cycle
    """
    
    def __init__(self):
        self.bedrock_client = boto3.client('bedrock-runtime', region_name=os.getenv('AWS_BEDROCK_REGION', 'us-east-1'))
        self.s3_client = boto3.client('s3')
        self.db_connection_string = os.getenv('CRDB_CONNECTION_STRING')
        self.threat_threshold = float(os.getenv('THREAT_THRESHOLD', '7.0'))
        
        if not self.db_connection_string:
            raise ValueError("CRDB_CONNECTION_STRING environment variable is required")
    
    def get_db_connection(self):
        """Get database connection"""
        return psycopg2.connect(self.db_connection_string, cursor_factory=RealDictCursor)
    
    async def observe(self, raw_log: Dict) -> SecurityEvent:
        """
        Step 1: Observe - Parse incoming log event
        """
        logger.info(f"Observing event: {raw_log.get('eventType', 'unknown')}")
        
        # Extract key fields from raw log (AWS CloudTrail format)
        event = SecurityEvent(
            event_id=None,  # Will be generated by database
            user_id=None,   # Will be resolved from username
            event_type=raw_log.get('eventName', 'unknown'),
            source_ip=raw_log.get('sourceIPAddress', '0.0.0.0'),
            action=raw_log.get('eventType', 'unknown'),
            timestamp=datetime.fromisoformat(raw_log.get('eventTime', datetime.utcnow().isoformat())),
            raw_log=raw_log
        )
        
        return event
    
    async def embed(self, event: SecurityEvent) -> SecurityEvent:
        """
        Step 2: Embed - Generate vector embedding using Bedrock Titan
        """
        logger.info(f"Generating embedding for event {event.event_type}")
        
        # Create a text representation of the event for embedding
        event_text = f"""
        Event Type: {event.event_type}
        Source IP: {event.source_ip}
        Action: {event.action}
        Timestamp: {event.timestamp}
        Raw Log: {json.dumps(event.raw_log)}
        """
        
        try:
            # Call Bedrock Titan for embedding
            response = self.bedrock_client.invoke_model(
                modelId='amazon.titan-embed-text-v2:0',
                body=json.dumps({
                    "inputText": event_text,
                    "dimensions": 1024
                })
            )
            
            response_body = json.loads(response['body'].read())
            event.embedding = response_body['embedding']
            
            logger.info(f"Generated embedding with {len(event.embedding)} dimensions")
            
        except Exception as e:
            logger.error(f"Failed to generate embedding: {str(e)}")
            # Fallback to random embedding for demo
            event.embedding = np.random.random(1024).tolist()
        
        return event
    
    async def retrieve_similar_events(self, event: SecurityEvent, limit: int = 10) -> List[Dict]:
        """
        Step 3: Retrieve - Find similar events using vector search
        """
        logger.info(f"Retrieving similar events for {event.event_type}")
        
        if not event.embedding:
            return []
        
        conn = self.get_db_connection()
        try:
            cursor = conn.cursor()
            
            # Vector similarity search query
            query = """
            SELECT 
                e.event_id,
                e.event_type,
                e.source_ip,
                e.action,
                e.timestamp,
                e.raw_log,
                e.embedding <-> %s::vector AS distance,
                u.username,
                u.risk_score
            FROM events e
            LEFT JOIN users u ON e.user_id = u.user_id
            WHERE e.timestamp > %s
            ORDER BY distance ASC
            LIMIT %s;
            """
            
            # Look back 90 days
            lookback_date = datetime.utcnow() - timedelta(days=90)
            
            cursor.execute(query, (event.embedding, lookback_date, limit))
            similar_events = cursor.fetchall()
            
            logger.info(f"Found {len(similar_events)} similar events")
            
            return [dict(row) for row in similar_events]
            
        except Exception as e:
            logger.error(f"Failed to retrieve similar events: {str(e)}")
            return []
        finally:
            conn.close()
    
    async def reason(self, event: SecurityEvent, similar_events: List[Dict]) -> ThreatDecision:
        """
        Step 4: Reason - Use Claude to analyze event in context
        """
        logger.info(f"Reasoning about event {event.event_type}")
        
        # Build context for Claude
        context = {
            "current_event": {
                "type": event.event_type,
                "source_ip": event.source_ip,
                "action": event.action,
                "timestamp": event.timestamp.isoformat(),
                "raw_log": event.raw_log
            },
            "similar_events": similar_events[:5],  # Top 5 most similar
            "analysis_request": "Analyze this event in context of similar historical events. Determine if this is part of a coordinated attack or APT campaign."
        }
        
        prompt = f"""
        You are Sentinel, an expert cybersecurity analyst. Analyze the following security event and determine if it's suspicious.
        
        Current Event:
        {json.dumps(context['current_event'], indent=2)}
        
        Similar Historical Events:
        {json.dumps(context['similar_events'], indent=2)}
        
        Instructions:
        1. Analyze the current event in the context of similar historical events
        2. Look for patterns that might indicate an Advanced Persistent Threat (APT)
        3. Consider factors like: unusual IP addresses, timing patterns, user behavior anomalies
        4. Provide a threat score from 0-10 (0=benign, 10=critical threat)
        5. Recommend an action: "ignore", "alert", "block"
        6. Explain your reasoning
        
        Respond in JSON format:
        {{
            "threat_score": <float>,
            "action": "<string>",
            "reasoning": "<string>",
            "confidence": <float>
        }}
        """
        
        try:
            # Call Claude via Bedrock
            response = self.bedrock_client.invoke_model(
                modelId='anthropic.claude-3-5-haiku-20241022-v1:0',
                body=json.dumps({
                    "anthropic_version": "bedrock-2023-05-31",
                    "max_tokens": 1000,
                    "messages": [
                        {
                            "role": "user",
                            "content": prompt
                        }
                    ]
                })
            )
            
            response_body = json.loads(response['body'].read())
            analysis = json.loads(response_body['content'][0]['text'])
            
            decision = ThreatDecision(
                event_id=event.event_id or "temp",
                threat_score=analysis.get('threat_score', 0.0),
                reasoning=analysis.get('reasoning', ''),
                action_taken=analysis.get('action', 'ignore'),
                similar_events=similar_events
            )
            
            logger.info(f"Threat analysis complete: score={decision.threat_score}, action={decision.action_taken}")
            
        except Exception as e:
            logger.error(f"Failed to reason about event: {str(e)}")
            # Fallback decision
            decision = ThreatDecision(
                event_id=event.event_id or "temp",
                threat_score=0.0,
                reasoning=f"Analysis failed: {str(e)}",
                action_taken="ignore",
                similar_events=similar_events
            )
        
        return decision
    
    async def act(self, decision: ThreatDecision) -> bool:
        """
        Step 5: Act - Take action based on threat decision
        """
        logger.info(f"Taking action: {decision.action_taken} (score: {decision.threat_score})")
        
        if decision.threat_score < self.threat_threshold:
            logger.info("Threat score below threshold, no action needed")
            return True
        
        action_success = True
        
        try:
            if decision.action_taken == "block":
                # In a real implementation, this would block the IP via AWS WAF
                logger.warning(f"BLOCKING IP - Threat detected with score {decision.threat_score}")
                # action_success = await self._block_ip(source_ip)
                
            elif decision.action_taken == "alert":
                # In a real implementation, this would send alerts via SNS
                logger.warning(f"ALERT - Suspicious activity detected with score {decision.threat_score}")
                # action_success = await self._send_alert(decision)
                
            else:
                logger.info("No action required")
                
        except Exception as e:
            logger.error(f"Failed to execute action: {str(e)}")
            action_success = False
        
        return action_success
    
    async def store(self, event: SecurityEvent, decision: ThreatDecision) -> str:
        """
        Step 6: Store - Save event and decision to CockroachDB
        """
        logger.info("Storing event and decision to database")
        
        conn = self.get_db_connection()
        try:
            cursor = conn.cursor()
            
            # First, ensure user exists or create one
            user_id = await self._ensure_user_exists(cursor, event.raw_log.get('userIdentity', {}).get('userName', 'unknown'))
            event.user_id = user_id
            
            # Insert event
            insert_event_query = """
            INSERT INTO events (user_id, event_type, source_ip, action, timestamp, raw_log, embedding)
            VALUES (%s, %s, %s, %s, %s, %s, %s::vector)
            RETURNING event_id;
            """
            
            cursor.execute(insert_event_query, (
                event.user_id,
                event.event_type,
                event.source_ip,
                event.action,
                event.timestamp,
                json.dumps(event.raw_log),
                event.embedding
            ))
            
            event_id = cursor.fetchone()['event_id']
            decision.event_id = event_id
            
            # Insert decision
            insert_decision_query = """
            INSERT INTO decisions (event_id, threat_score, reasoning, action_taken, outcome)
            VALUES (%s, %s, %s, %s, %s);
            """
            
            cursor.execute(insert_decision_query, (
                event_id,
                decision.threat_score,
                decision.reasoning,
                decision.action_taken,
                'success'  # Assume success for now
            ))
            
            conn.commit()
            logger.info(f"Stored event {event_id} and decision")
            
            return event_id
            
        except Exception as e:
            logger.error(f"Failed to store event: {str(e)}")
            conn.rollback()
            raise
        finally:
            conn.close()
    
    async def _ensure_user_exists(self, cursor, username: str) -> str:
        """Ensure user exists in database, create if not"""
        # Check if user exists
        cursor.execute("SELECT user_id FROM users WHERE username = %s", (username,))
        result = cursor.fetchone()
        
        if result:
            return result['user_id']
        
        # Create new user with random baseline embedding
        baseline_embedding = np.random.random(1024).tolist()
        
        cursor.execute("""
            INSERT INTO users (username, baseline_embedding, risk_score)
            VALUES (%s, %s::vector, %s)
            RETURNING user_id;
        """, (username, baseline_embedding, 0.5))
        
        return cursor.fetchone()['user_id']
    
    async def process_event(self, raw_log: Dict) -> ThreatDecision:
        """
        Main agent processing pipeline - executes the full O.E.R.R.A.S cycle
        """
        logger.info("Starting Sentinel agent processing cycle")
        
        try:
            # Complete agent workflow
            event = await self.observe(raw_log)
            event = await self.embed(event)
            similar_events = await self.retrieve_similar_events(event)
            decision = await self.reason(event, similar_events)
            await self.act(decision)
            event_id = await self.store(event, decision)
            
            logger.info(f"Agent cycle complete for event {event_id}")
            return decision
            
        except Exception as e:
            logger.error(f"Agent processing failed: {str(e)}")
            raise

# Lambda handler
def lambda_handler(event, context):
    """AWS Lambda entry point"""
    agent = SentinelAgent()
    
    try:
        # Process the event
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        
        decision = loop.run_until_complete(agent.process_event(event))
        
        return {
            'statusCode': 200,
            'body': json.dumps({
                'event_id': decision.event_id,
                'threat_score': decision.threat_score,
                'action_taken': decision.action_taken,
                'reasoning': decision.reasoning
            })
        }
        
    except Exception as e:
        logger.error(f"Lambda execution failed: {str(e)}")
        return {
            'statusCode': 500,
            'body': json.dumps({
                'error': str(e)
            })
        }
    finally:
        loop.close()